### model
model_name_or_path: /model/MLPerf-Pruned-Llama-3.1-405B-Instruct/
trust_remote_code: true

### save gpu memory
#enable_liger_kernel: true
#flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 16
lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: mlperf_train_demo
template: empty
cutoff_len: 18000
overwrite_cache: true
preprocessing_num_workers: 64
dataloader_num_workers: 64

### output
output_dir: saves/llama3-405b_prune_finetune/lora/sft
logging_steps: 1
save_steps: 5
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 5
learning_rate: 2.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
gradient_checkpointing: true
flash_attn: fa2
max_grad_norm: 1.0  # <--- gradient clipping
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
eval_dataset: mlperf_eval_demo
# val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 10
